import type { RolodexContact } from "./rolodex-types";

export const SEED_CONTACTS: RolodexContact[] = [
  {
    id: "1",
    firstName: "Marcus",
    lastName: "Chen",
    avatar: "",
    email: "marcus@chenfamilyrestaurant.com",
    phone: "+15025551234",
    company: "Chen Family Restaurant",
    title: "Owner",
    city: "Louisville",
    state: "KY",
    relationshipType: "client",
    tags: ["restaurant", "vip", "louisville"],
    howWeMet: "Cold email campaign",
    metDate: "2025-09-15",
    interests: "Golf, bourbon, family",
    spouse: "Sarah Chen",
    birthday: "1985-03-22",
    college: "University of Louisville",
    relationshipScore: 92,
    importanceScore: 95,
    interactions: [
      { id: "i1", type: "call", date: "2026-03-12", summary: "Discussed Q2 ad strategy, wants to increase budget", createdAt: "2026-03-12" },
      { id: "i2", type: "meeting", date: "2026-03-05", summary: "Lunch at his restaurant, reviewed new menu launch campaign", createdAt: "2026-03-05" },
      { id: "i3", type: "email", date: "2026-02-28", summary: "Sent monthly performance report", createdAt: "2026-02-28" },
    ],
    notes: [
      { id: "n1", content: "Marcus mentioned he's opening a second location in Lexington Q3. Big opportunity for expanded services.", pinned: true, createdAt: "2026-03-05", updatedAt: "2026-03-05" },
      { id: "n2", content: "Prefers calls over email. Best time to reach: Tuesday/Thursday mornings.", createdAt: "2026-02-15", updatedAt: "2026-02-15" },
    ],
    facts: [
      { id: "f1", category: "personal", label: "Favorite bourbon", value: "Woodford Reserve" },
      { id: "f2", category: "business", label: "Annual revenue", value: "~$2.5M" },
      { id: "f3", category: "personal", label: "Kids", value: "2 daughters (8 and 5)" },
    ],
    groups: [], groups: ["Clients", "Louisville", "VIP"], connections: ["2", "5"],
    lastContactedAt: "2026-03-12",
    nextFollowUp: "2026-03-19",
    source: "Cold Email",
    aiSummary: "Top client and personal friend. Opening second location in Lexington — huge growth opportunity. Very loyal, responds best to calls.",
    createdAt: "2025-09-15",
    updatedAt: "2026-03-12",
    archived: false,
  },
  {
    id: "2",
    firstName: "Aisha",
    lastName: "Patel",
    email: "aisha@spicerouteky.com",
    phone: "+15025559876",
    company: "Spice Route",
    title: "Co-Owner",
    city: "Louisville",
    state: "KY",
    relationshipType: "client",
    tags: ["restaurant", "louisville", "referral-source"],
    howWeMet: "Referred by Marcus Chen",
    introducedBy: "Marcus Chen",
    metDate: "2025-11-20",
    interests: "Yoga, cooking competitions, travel",
    spouse: "Raj Patel",
    birthday: "1990-07-14",
    relationshipScore: 78,
    importanceScore: 80,
    interactions: [
      { id: "i4", type: "meeting", date: "2026-03-10", summary: "Reviewed website redesign mockups", createdAt: "2026-03-10" },
      { id: "i5", type: "text", date: "2026-03-08", summary: "She texted about adding online ordering", createdAt: "2026-03-08" },
    ],
    notes: [
      { id: "n3", content: "Aisha wants to be featured on our case study page. Said she'd do a video testimonial.", pinned: true, createdAt: "2026-03-10", updatedAt: "2026-03-10" },
    ],
    facts: [
      { id: "f4", category: "business", label: "Current provider", value: "Was on SpotHopper" },
      { id: "f5", category: "personal", label: "Diet", value: "Vegetarian" },
    ],
    groups: [], groups: ["Clients", "Louisville"], groups: ["Prospects", "Louisville"], connections: ["1"],
    lastContactedAt: "2026-03-10",
    source: "Referral",
    aiSummary: "Enthusiastic client referred by Marcus. Great testimonial candidate. Wants to add online ordering ASAP.",
    createdAt: "2025-11-20",
    updatedAt: "2026-03-10",
    archived: false,
  },
  {
    id: "3",
    firstName: "Jake",
    lastName: "Morrison",
    email: "jake@morrisonventures.com",
    phone: "+15025553456",
    company: "Morrison Ventures",
    title: "Managing Partner",
    city: "Louisville",
    state: "KY",
    relationshipType: "investor",
    tags: ["vip", "louisville", "investor", "potential"],
    howWeMet: "UofL entrepreneurship event",
    metDate: "2025-10-05",
    interests: "Startups, bourbon, horse racing",
    college: "Vanderbilt",
    birthday: "1978-11-03",
    relationshipScore: 65,
    importanceScore: 98,
    interactions: [
      { id: "i6", type: "meeting", date: "2026-02-20", summary: "Coffee meeting, discussed Derby Digital growth trajectory", createdAt: "2026-02-20" },
      { id: "i7", type: "email", date: "2026-03-01", summary: "Sent one-pager about DerbyFlow", createdAt: "2026-03-01" },
    ],
    notes: [
      { id: "n4", content: "Jake is interested in DerbyFlow but wants to see product-market fit first. Mentioned he typically invests $250K-$500K in early stage.", pinned: true, createdAt: "2026-02-20", updatedAt: "2026-02-20" },
      { id: "n5", content: "His wife's birthday is in April — send a card.", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
    ],
    facts: [
      { id: "f6", category: "business", label: "Fund size", value: "$15M early-stage fund" },
      { id: "f7", category: "personal", label: "Favorite restaurant", value: "610 Magnolia" },
      { id: "f8", category: "business", label: "Portfolio", value: "12 companies, mostly SaaS" },
    ],
    groups: [], groups: ["Investors", "Louisville"], connections: ["4"],
    lastContactedAt: "2026-03-01",
    nextFollowUp: "2026-03-20",
    source: "Event",
    aiSummary: "Potential investor for DerbyFlow. Very connected in Louisville startup scene. Needs to see PMF before committing. Worth nurturing.",
    createdAt: "2025-10-05",
    updatedAt: "2026-03-01",
    archived: false,
  },
  {
    id: "4",
    firstName: "Sofia",
    lastName: "Reyes",
    email: "sofia@uofl.edu",
    phone: "+15025557890",
    company: "University of Louisville",
    title: "Professor, Entrepreneurship",
    city: "Louisville",
    state: "KY",
    relationshipType: "mentor",
    tags: ["louisville", "school", "mentor"],
    howWeMet: "Entrepreneurship class",
    metDate: "2025-08-20",
    college: "Stanford",
    birthday: "1975-05-18",
    relationshipScore: 85,
    importanceScore: 75,
    interactions: [
      { id: "i8", type: "meeting", date: "2026-03-11", summary: "Office hours — discussed pricing strategy for restaurant niche", createdAt: "2026-03-11" },
    ],
    notes: [
      { id: "n6", content: "Sofia suggested I look into vertical SaaS benchmarks. Sent me a list of resources.", createdAt: "2026-03-11", updatedAt: "2026-03-11" },
    ],
    facts: [
      { id: "f9", category: "business", label: "Research focus", value: "Platform businesses, marketplace dynamics" },
    ],
    groups: [], groups: ["Louisville", "School"], connections: ["3"],
    lastContactedAt: "2026-03-11",
    source: "School",
    aiSummary: "Key mentor at UofL. Deep expertise in platform businesses. Connected to Jake Morrison and the Louisville investor scene.",
    createdAt: "2025-08-20",
    updatedAt: "2026-03-11",
    archived: false,
  },
  {
    id: "5",
    firstName: "Dre",
    lastName: "Thompson",
    email: "dre@smokeandbarrel502.com",
    phone: "+15025554321",
    company: "Smoke & Barrel 502",
    title: "Owner",
    city: "Louisville",
    state: "KY",
    relationshipType: "prospect",
    tags: ["restaurant", "louisville", "hot-lead", "bbq"],
    howWeMet: "Marcus Chen introduction",
    introducedBy: "Marcus Chen",
    metDate: "2026-02-01",
    interests: "BBQ competitions, craft beer, cars",
    relationshipScore: 55,
    importanceScore: 70,
    interactions: [
      { id: "i9", type: "call", date: "2026-03-09", summary: "Demo call — very interested in DerbyFlow ordering system", createdAt: "2026-03-09" },
      { id: "i10", type: "text", date: "2026-03-13", summary: "Texted asking about pricing, sent him the deck", createdAt: "2026-03-13" },
    ],
    notes: [
      { id: "n7", content: "Dre is on Toast right now and paying $300/mo. Hates their customer service. Hot lead.", pinned: true, createdAt: "2026-03-09", updatedAt: "2026-03-09" },
    ],
    facts: [
      { id: "f10", category: "business", label: "Current provider", value: "Toast ($300/mo)" },
      { id: "f11", category: "business", label: "Monthly revenue", value: "~$80K" },
    ],
    groups: [], groups: ["Clients", "Louisville"], groups: ["Prospects", "Louisville"], connections: ["1"],
    lastContactedAt: "2026-03-13",
    nextFollowUp: "2026-03-15",
    source: "Referral",
    aiSummary: "Hot prospect. Unhappy with Toast, interested in DerbyFlow. Introduced by Marcus. Close this deal ASAP.",
    createdAt: "2026-02-01",
    updatedAt: "2026-03-13",
    archived: false,
  },
  {
    id: "6",
    firstName: "Hamza",
    lastName: "Ali",
    email: "hamza@derbydigital.us",
    company: "Derby Digital",
    title: "Landing Page Designer",
    city: "Remote",
    relationshipType: "team",
    tags: ["team", "designer"],
    howWeMet: "Hired",
    relationshipScore: 80,
    interactions: [
      { id: "i11", type: "meeting", date: "2026-03-12", summary: "Weekly sync — working on Bluegrass Garage Door page", createdAt: "2026-03-12" },
    ],
    notes: [],
    facts: [
      { id: "f12", category: "work", label: "Tools", value: "Framer, WordPress/Elementor" },
    ],
    groups: [], connections: [],
    lastContactedAt: "2026-03-12",
    source: "Hire",
    createdAt: "2026-01-15",
    updatedAt: "2026-03-12",
    archived: false,
  },
  {
    id: "7",
    firstName: "Tyler",
    lastName: "Brooks",
    email: "tyler.brooks@gmail.com",
    phone: "+15025558765",
    company: "",
    title: "",
    city: "Louisville",
    state: "KY",
    relationshipType: "friend",
    tags: ["louisville", "school", "close-friend"],
    howWeMet: "UofL freshman year",
    college: "University of Louisville",
    birthday: "2005-08-30",
    interests: "Basketball, gaming, crypto",
    relationshipScore: 90,
    importanceScore: 40,
    interactions: [
      { id: "i12", type: "social", date: "2026-03-13", summary: "Hung out at campus", createdAt: "2026-03-13" },
      { id: "i13", type: "text", date: "2026-03-11", summary: "Planning weekend hangout", createdAt: "2026-03-11" },
    ],
    notes: [
      { id: "n8", content: "Tyler mentioned his uncle owns 3 restaurants in Bowling Green. Potential intro.", createdAt: "2026-03-13", updatedAt: "2026-03-13" },
    ],
    facts: [],
    groups: [], groups: ["Friends", "School"], connections: ["8"],
    lastContactedAt: "2026-03-13",
    source: "School",
    createdAt: "2025-08-20",
    updatedAt: "2026-03-13",
    archived: false,
  },
  {
    id: "8",
    firstName: "Nima",
    lastName: "Asgari",
    email: "nima@asgari.dev",
    phone: "+15025559999",
    company: "Asgari Digital",
    title: "Developer",
    city: "Louisville",
    state: "KY",
    relationshipType: "partner",
    tags: ["louisville", "developer", "ai"],
    howWeMet: "Tech meetup",
    metDate: "2025-10-15",
    interests: "AI, coding, startups",
    relationshipScore: 72,
    importanceScore: 65,
    interactions: [
      { id: "i14", type: "meeting", date: "2026-03-08", summary: "Discussed potential collaboration on AI tools", createdAt: "2026-03-08" },
    ],
    notes: [],
    facts: [],
    groups: [], groups: ["Louisville"], connections: ["7"],
    lastContactedAt: "2026-03-08",
    source: "Event",
    createdAt: "2025-10-15",
    updatedAt: "2026-03-08",
    archived: false,
  },
  {
    id: "9",
    firstName: "Lisa",
    lastName: "Drayton",
    email: "bbmtryoncatering@gmail.com",
    phone: "+17046540329",
    company: "BBM Tryon Catering",
    title: "Owner",
    city: "Charlotte",
    state: "NC",
    relationshipType: "prospect",
    tags: ["restaurant", "cold-email", "spothopper", "interested"],
    howWeMet: "Cold email campaign",
    metDate: "2026-03-13",
    relationshipScore: 35,
    importanceScore: 60,
    interactions: [
      { id: "i15", type: "email", date: "2026-03-13", summary: "Replied interested, gave phone number, wants a call", createdAt: "2026-03-13" },
    ],
    notes: [
      { id: "n9", content: "Currently on SpotHopper. Interested in conversation and more info. Call her at 704-654-0329.", pinned: true, createdAt: "2026-03-13", updatedAt: "2026-03-13" },
    ],
    facts: [
      { id: "f13", category: "business", label: "Current provider", value: "SpotHopper" },
    ],
    groups: [], connections: [],
    lastContactedAt: "2026-03-13",
    nextFollowUp: "2026-03-14",
    source: "Cold Email",
    aiSummary: "New interested lead from SpotHopper campaign. Gave phone number proactively — high intent. Call ASAP.",
    createdAt: "2026-03-13",
    updatedAt: "2026-03-13",
    archived: false,
  },
  {
    id: "10",
    firstName: "Mom",
    lastName: "",
    phone: "+15025550001",
    company: "",
    title: "",
    city: "Louisville",
    state: "KY",
    relationshipType: "family",
    tags: ["family"],
    relationshipScore: 100,
    importanceScore: 100,
    interactions: [
      { id: "i16", type: "call", date: "2026-03-12", summary: "Called to check in", createdAt: "2026-03-12" },
    ],
    notes: [],
    facts: [],
    groups: [], connections: [],
    lastContactedAt: "2026-03-12",
    createdAt: "2025-01-01",
    updatedAt: "2026-03-12",
    archived: false,
  },
];
