import type { RolodexContact } from "./rolodex-types";

export const SEED_CONTACTS: RolodexContact[] = [
  {
    id: "1",
    firstName: "Marcus",
    lastName: "Chen",
    email: "marcus@chenfamilyrestaurant.com",
    phone: "+15025551234",
    company: "Chen Family Restaurant",
    title: "Owner",
    city: "Louisville",
    state: "KY",
    country: "US",
    hometown: "Louisville",
    website: "https://chenfamilyrestaurant.com",
    linkedin: "linkedin.com/in/marcuschen",
    relationshipType: "client",
    tags: ["restaurant", "vip", "louisville"],
    howWeMet: "Cold email campaign — he replied within 2 hours, set up a call same day",
    metDate: "2025-09-15",
    interests: "Golf, bourbon, family dinners, Louisville Cardinals basketball",
    spouse: "Sarah Chen",
    children: "2 daughters (Lily, 8 and Emma, 5)",
    birthday: "1985-03-22",
    college: "University of Louisville",
    relationshipScore: 92,
    importanceScore: 95,
    interactions: [
      { id: "i1", type: "call", date: "2026-03-12", summary: "Discussed Q2 ad strategy, wants to increase budget to $3K/mo", direction: "outbound", duration: 1260, createdAt: "2026-03-12" },
      { id: "i1b", type: "call", date: "2026-03-05T14:00:00", summary: "Quick check-in before lunch meeting", direction: "outbound", duration: 420, createdAt: "2026-03-05" },
      { id: "i2", type: "meeting", date: "2026-03-05", summary: "Lunch at his restaurant, reviewed new menu launch campaign", location: "Chen Family Restaurant", attendees: ["Marcus Chen", "Sarah Chen"], details: "Tried the new dim sum menu. Sarah joined for dessert. Discussed expansion plans for Lexington location. He wants a full digital package for the new spot.", createdAt: "2026-03-05" },
      { id: "i3", type: "email", date: "2026-02-28", summary: "Sent monthly performance report — 47% increase in online orders", subject: "February Performance Report", createdAt: "2026-02-28" },
      { id: "i3b", type: "email", date: "2026-02-15", summary: "He forwarded a competitor's ad asking if we can do better", subject: "Re: Check this out", sentiment: "positive", createdAt: "2026-02-15" },
      { id: "i3c", type: "text", date: "2026-03-10", summary: "Sent photos of his restaurant's new patio setup", createdAt: "2026-03-10" },
      { id: "i3d", type: "meeting", date: "2026-01-15", summary: "Quarterly business review at his restaurant", location: "Chen Family Restaurant", duration: 3600, createdAt: "2026-01-15" },
      { id: "i3e", type: "call", date: "2026-01-28", summary: "Called about Super Bowl ad campaign", direction: "inbound", duration: 900, createdAt: "2026-01-28" },
      { id: "i3f", type: "social", date: "2026-02-14", summary: "Liked and commented on his restaurant's Valentine's Day post", createdAt: "2026-02-14" },
      { id: "i3g", type: "gift", date: "2025-12-20", summary: "Sent a bottle of Woodford Reserve for Christmas", createdAt: "2025-12-20" },
      { id: "i3h", type: "milestone", date: "2026-01-01", summary: "1 year anniversary as a client", createdAt: "2026-01-01" },
    ],
    notes: [
      { id: "n1", content: "Marcus mentioned he's opening a second location in Lexington Q3. Big opportunity for expanded services. Budget for new location: $5K/mo marketing.", pinned: true, category: "business", createdAt: "2026-03-05", updatedAt: "2026-03-05" },
      { id: "n2", content: "Prefers calls over email. Best time to reach: Tuesday/Thursday mornings before 11am.", category: "general", createdAt: "2026-02-15", updatedAt: "2026-02-15" },
      { id: "n2b", content: "His daughter Lily's birthday is March 22 — same as his. He does a big family party every year.", category: "personal", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
      { id: "n2c", content: "Potential intro to his friend who owns 4 restaurants in Nashville. Need to ask him next call.", category: "follow-up", pinned: true, createdAt: "2026-03-05", updatedAt: "2026-03-05" },
    ],
    facts: [
      { id: "f1", category: "personal", label: "Favorite bourbon", value: "Woodford Reserve" },
      { id: "f2", category: "business", label: "Annual revenue", value: "~$2.5M" },
      { id: "f3", category: "personal", label: "Kids", value: "Lily (8) and Emma (5)" },
      { id: "f3b", category: "personal", label: "Golf handicap", value: "12" },
      { id: "f3c", category: "business", label: "Peak hours", value: "Fri-Sat 6-9pm" },
      { id: "f3d", category: "personal", label: "Favorite team", value: "Louisville Cardinals" },
      { id: "f3e", category: "business", label: "Staff size", value: "22 employees" },
      { id: "f3f", category: "personal", label: "Anniversary", value: "June 15" },
    ],
    opportunities: [
      { id: "o1", title: "Lexington location launch", type: "business", status: "open", value: "$5K/mo", notes: "Full digital package for new location opening Q3", nextStep: "Send proposal after lease is signed", createdAt: "2026-03-05", updatedAt: "2026-03-05" },
      { id: "o2", title: "Nashville restaurant owner intro", type: "intro", status: "open", notes: "Marcus's friend owns 4 restaurants in Nashville", nextStep: "Ask Marcus for intro on next call", createdAt: "2026-03-05", updatedAt: "2026-03-05" },
    ],
    aiInsights: [
      { id: "ai1", type: "follow-up-suggested", content: "Marcus mentioned Lexington lease signing this month — follow up to send proposal", confidence: 0.92, actionable: true, createdAt: "2026-03-12" },
      { id: "ai2", type: "fact-extracted", content: "Marcus's daughter Lily shares his birthday (March 22) — birthday coming up in 10 days", confidence: 0.95, actionable: true, createdAt: "2026-03-12" },
    ],
    groups: ["Clients", "Louisville", "VIP"],
    connections: ["2", "5"],
    stayInTouch: { frequency: "weekly" },
    lastContactedAt: "2026-03-12",
    nextFollowUp: "2026-03-19",
    source: "Cold Email",
    aiSummary: "Marcus is a highly engaged VIP client whose Chen Family Restaurant is thriving, evidenced by a 47% increase in online orders and his proactive communication. We're in a strong position, so let's finalize his Q2 ad strategy with the increased budget, proactively plan for his Lexington expansion, and remember his and Lily's shared March 22nd birthday while subtly exploring that Nashville intro on our next call.",
    aiBriefing: "Marcus is your highest-value client at ~$2.5M annual revenue. He's opening a second location in Lexington Q3 and mentioned wanting a full digital package ($5K/mo). The lease should be signed soon — ask for an update. His birthday and his daughter Lily's birthday are both March 22 (coming up). He mentioned a friend who owns 4 restaurants in Nashville — ask for that intro. He prefers calls on Tue/Thu mornings. Last interaction was a strategy call 1 day ago where he wants to increase ad budget to $3K/mo.",
    createdAt: "2025-09-15",
    updatedAt: "2026-03-12",
    archived: false,
  },
  {
    id: "2",
    firstName: "Aisha",
    lastName: "Patel",
    email: "aisha@spicerouteky.com",
    phone: "+15025559876",
    company: "Spice Route",
    title: "Co-Owner",
    city: "Louisville",
    state: "KY",
    country: "US",
    website: "https://spicerouteky.com",
    instagram: "spicerouteky",
    relationshipType: "client",
    tags: ["restaurant", "louisville", "referral-source"],
    howWeMet: "Referred by Marcus Chen — she called the same day Marcus mentioned us",
    introducedBy: "Marcus Chen",
    metDate: "2025-11-20",
    interests: "Yoga, cooking competitions, travel to India, food photography",
    spouse: "Raj Patel",
    birthday: "1990-07-14",
    college: "Purdue University",
    relationshipScore: 78,
    importanceScore: 80,
    interactions: [
      { id: "i4", type: "meeting", date: "2026-03-10", summary: "Reviewed website redesign mockups — loved the new menu layout", location: "Spice Route", attendees: ["Aisha Patel", "Raj Patel"], createdAt: "2026-03-10" },
      { id: "i5", type: "text", date: "2026-03-08", summary: "She texted about adding online ordering — wants DerbyFlow", createdAt: "2026-03-08" },
      { id: "i5b", type: "email", date: "2026-02-20", summary: "Sent her the monthly analytics report", subject: "January Results - Spice Route", createdAt: "2026-02-20" },
      { id: "i5c", type: "call", date: "2026-02-10", summary: "Quick call about Valentine's Day promotion", direction: "inbound", duration: 600, createdAt: "2026-02-10" },
      { id: "i5d", type: "social", date: "2026-03-01", summary: "She tagged Derby Digital in an Instagram story about her new website", createdAt: "2026-03-01" },
    ],
    notes: [
      { id: "n3", content: "Aisha wants to be featured on our case study page. Said she'd do a video testimonial. Schedule this for April.", pinned: true, category: "business", createdAt: "2026-03-10", updatedAt: "2026-03-10" },
      { id: "n3b", content: "Raj handles the finances, Aisha handles marketing decisions. Always CC both on invoices.", category: "business", createdAt: "2026-01-15", updatedAt: "2026-01-15" },
    ],
    facts: [
      { id: "f4", category: "business", label: "Previous provider", value: "SpotHopper" },
      { id: "f5", category: "personal", label: "Diet", value: "Vegetarian" },
      { id: "f5b", category: "business", label: "Cuisine", value: "Indian fusion" },
      { id: "f5c", category: "personal", label: "Home country", value: "Parents from Gujarat, India" },
    ],
    opportunities: [
      { id: "o3", title: "Video testimonial / case study", type: "collaboration", status: "open", notes: "She volunteered — great social proof", nextStep: "Schedule video shoot in April", createdAt: "2026-03-10", updatedAt: "2026-03-10" },
      { id: "o4", title: "DerbyFlow online ordering", type: "business", status: "in-progress", value: "$200/mo", notes: "Wants to switch from SpotHopper to DerbyFlow", nextStep: "Demo DerbyFlow next meeting", createdAt: "2026-03-08", updatedAt: "2026-03-08" },
    ],
    aiInsights: [
      { id: "ai3", type: "relationship-insight", content: "Aisha has been increasingly engaged — 5 interactions in the last 30 days, up from 2 the month before", confidence: 0.88, actionable: false, createdAt: "2026-03-10" },
    ],
    groups: ["Clients", "Louisville"],
    connections: ["1"],
    lastContactedAt: "2026-03-10",
    source: "Referral",
    aiSummary: "Aisha is a highly engaged and satisfied marketing lead at Spice Route, enthusiastic about our work, especially the new menu layout, and keen to adopt DerbyFlow for online ordering. Our relationship is clearly thriving, with her already tagging us on social media and wanting to be featured in a case study. Let's schedule her video testimonial for April and ensure a smooth DerbyFlow implementation, remembering to CC Raj on all invoices.",
    aiBriefing: "Aisha is a highly engaged client who was referred by Marcus Chen. She co-owns Spice Route (Indian fusion) with her husband Raj. She's interested in switching to DerbyFlow for online ordering and has volunteered to do a video testimonial. She's vegetarian, loves yoga, and is very active on Instagram. Always CC Raj on financial matters. She tagged Derby Digital in an Instagram story recently — great organic advocacy.",
    createdAt: "2025-11-20",
    updatedAt: "2026-03-10",
    archived: false,
  },
  {
    id: "3",
    firstName: "Jake",
    lastName: "Morrison",
    email: "jake@morrisonventures.com",
    phone: "+15025553456",
    company: "Morrison Ventures",
    title: "Managing Partner",
    city: "Louisville",
    state: "KY",
    country: "US",
    website: "https://morrisonventures.com",
    linkedin: "linkedin.com/in/jakemorrison",
    twitter: "jakemorrisonvc",
    relationshipType: "investor",
    tags: ["vip", "louisville", "investor", "potential"],
    howWeMet: "UofL entrepreneurship event — he approached me after my pitch",
    metDate: "2025-10-05",
    interests: "Startups, bourbon, horse racing, Kentucky Derby",
    college: "Vanderbilt",
    birthday: "1978-11-03",
    spouse: "Catherine Morrison",
    relationshipScore: 65,
    importanceScore: 98,
    interactions: [
      { id: "i6", type: "meeting", date: "2026-02-20", summary: "Coffee at Please & Thank You — discussed Derby Digital growth trajectory and DerbyFlow roadmap", location: "Please & Thank You Coffee", duration: 2700, createdAt: "2026-02-20" },
      { id: "i7", type: "email", date: "2026-03-01", summary: "Sent one-pager about DerbyFlow with updated metrics", subject: "DerbyFlow - Updated Deck", createdAt: "2026-03-01" },
      { id: "i7b", type: "email", date: "2026-03-08", summary: "He replied asking about customer retention rates", subject: "Re: DerbyFlow - Updated Deck", needsReply: true, createdAt: "2026-03-08" },
      { id: "i7c", type: "social", date: "2026-02-25", summary: "He shared our blog post about restaurant digital marketing on LinkedIn", createdAt: "2026-02-25" },
    ],
    notes: [
      { id: "n4", content: "Jake is interested in DerbyFlow but wants to see product-market fit first. Mentioned he typically invests $250K-$500K in early stage. Wants to see 50+ paying customers before considering.", pinned: true, category: "business", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
      { id: "n5", content: "His wife Catherine's birthday is in April — he mentioned it casually. Send a card.", category: "personal", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
      { id: "n5b", content: "He sits on the board of 3 companies and is advisor to 5 more. Very well-connected in Louisville business scene.", category: "business", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
    ],
    facts: [
      { id: "f6", category: "business", label: "Fund size", value: "$15M early-stage fund" },
      { id: "f7", category: "personal", label: "Favorite restaurant", value: "610 Magnolia" },
      { id: "f8", category: "business", label: "Portfolio", value: "12 companies, mostly SaaS" },
      { id: "f8b", category: "business", label: "Check size", value: "$250K-$500K" },
      { id: "f8c", category: "personal", label: "Kentucky Derby box", value: "Has a suite — invites portfolio founders" },
      { id: "f8d", category: "business", label: "Board seats", value: "3 active boards" },
    ],
    opportunities: [
      { id: "o5", title: "DerbyFlow investment — $250K-$500K", type: "deal", status: "open", value: "$250K-$500K", notes: "Wants to see 50+ paying customers first", nextStep: "Reply to his retention rate question with data", createdAt: "2026-02-20", updatedAt: "2026-03-08" },
      { id: "o6", title: "Kentucky Derby suite invite", type: "strategic", status: "open", notes: "He invites portfolio founders to his Derby suite — getting invited = being in the inner circle", nextStep: "Continue building relationship", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
    ],
    aiInsights: [
      { id: "ai4", type: "open-loop", content: "Jake asked about customer retention rates on March 8 — still unanswered (5 days ago)", confidence: 0.95, actionable: true, createdAt: "2026-03-13" },
      { id: "ai5", type: "follow-up-suggested", content: "Consider inviting Jake to see a client using DerbyFlow in action — would address his PMF concerns", confidence: 0.8, actionable: true, createdAt: "2026-03-13" },
    ],
    groups: ["Investors", "Louisville", "VIP"],
    connections: ["4"],
    stayInTouch: { frequency: "biweekly" },
    lastContactedAt: "2026-03-08",
    nextFollowUp: "2026-03-15",
    source: "Event",
    aiSummary: "Jake is a highly engaged Louisville investor keen on DerbyFlow, but he's waiting to see clear product-market fit, specifically 50+ paying customers, before considering an investment. Our next steps are to focus on achieving those customer metrics and follow up on retention rates, while also strengthening our personal connection by remembering his wife Catherine's April birthday.",
    aiBriefing: "Jake Morrison runs a $15M early-stage fund investing $250K-$500K checks, mostly in SaaS. He's interested in DerbyFlow but wants to see 50+ paying customers before investing. He asked about customer retention rates on March 8 and you haven't replied yet — this is urgent. He shared your blog post on LinkedIn recently (good sign). His wife Catherine has a birthday in April. He has a Kentucky Derby suite and invites portfolio founders. Connected to Sofia Reyes at UofL. Went to Vanderbilt. Favorite restaurant: 610 Magnolia.",
    createdAt: "2025-10-05",
    updatedAt: "2026-03-08",
    archived: false,
  },
  {
    id: "4",
    firstName: "Sofia",
    lastName: "Reyes",
    email: "sofia@uofl.edu",
    phone: "+15025557890",
    company: "University of Louisville",
    title: "Professor, Entrepreneurship",
    city: "Louisville",
    state: "KY",
    country: "US",
    linkedin: "linkedin.com/in/sofiareyes",
    relationshipType: "mentor",
    tags: ["louisville", "school", "mentor"],
    howWeMet: "Entrepreneurship class — she pulled me aside after my first pitch and offered to mentor",
    metDate: "2025-08-20",
    college: "Stanford",
    birthday: "1975-05-18",
    interests: "EdTech, platform economics, hiking, wine",
    relationshipScore: 85,
    importanceScore: 75,
    interactions: [
      { id: "i8", type: "meeting", date: "2026-03-11", summary: "Office hours — discussed pricing strategy for restaurant niche, she suggested tiered pricing model", location: "UofL - College of Business", duration: 1800, createdAt: "2026-03-11" },
      { id: "i8b", type: "email", date: "2026-03-02", summary: "She sent a list of vertical SaaS benchmarks and research papers", subject: "Resources for your platform analysis", createdAt: "2026-03-02" },
      { id: "i8c", type: "meeting", date: "2026-02-11", summary: "Monthly mentor meeting — reviewed financial projections", location: "UofL - College of Business", duration: 2400, recurring: true, createdAt: "2026-02-11" },
      { id: "i8d", type: "email", date: "2026-01-20", summary: "She introduced me to a Stanford alum running a restaurant tech company", subject: "Intro: Alex Kim - PlateCraft", participants: ["Alex Kim"], createdAt: "2026-01-20" },
    ],
    notes: [
      { id: "n6", content: "Sofia suggested I look into vertical SaaS benchmarks. Sent me a list of resources. Her key insight: 'Your retention will make or break the investment case.'", pinned: true, category: "business", createdAt: "2026-03-11", updatedAt: "2026-03-11" },
      { id: "n6b", content: "She knows Jake Morrison well — they co-teach a course. Could be a strategic ally for the investment conversation.", category: "business", createdAt: "2026-02-20", updatedAt: "2026-02-20" },
    ],
    facts: [
      { id: "f9", category: "business", label: "Research focus", value: "Platform businesses, marketplace dynamics" },
      { id: "f9b", category: "business", label: "Stanford connection", value: "Active alumni network, makes intros" },
      { id: "f9c", category: "personal", label: "Coffee order", value: "Oat milk latte" },
    ],
    opportunities: [
      { id: "o7", title: "Stanford alumni network intros", type: "intro", status: "in-progress", notes: "She already introduced Alex Kim from PlateCraft", nextStep: "Follow up with Alex Kim", createdAt: "2026-01-20", updatedAt: "2026-01-20" },
    ],
    aiInsights: [],
    groups: ["Mentors", "Louisville", "School"],
    connections: ["3"],
    stayInTouch: { frequency: "biweekly" },
    lastContactedAt: "2026-03-11",
    source: "School",
    aiSummary: "Sofia is an invaluable mentor, a sharp UofL Professor specializing in platform economics and vertical SaaS, who actively supports my venture with strategic insights and powerful introductions. Our relationship is thriving, so continue leveraging her expertise on pricing and retention, follow up on the Stanford alum intro, and strategically engage her connection to Jake Morrison as investment conversations progress.",
    aiBriefing: "Sofia is your entrepreneurship professor and mentor at UofL. She went to Stanford and has an active alumni network she uses to make intros (already connected you with Alex Kim at PlateCraft). She co-teaches with Jake Morrison, making her a strategic ally for the investment conversation. Her key advice: focus on retention metrics. She suggested tiered pricing for the restaurant niche. She likes oat milk lattes. Monthly mentor meetings at UofL.",
    createdAt: "2025-08-20",
    updatedAt: "2026-03-11",
    archived: false,
  },
  {
    id: "5",
    firstName: "Dre",
    lastName: "Thompson",
    email: "dre@smokeandbarrel502.com",
    phone: "+15025554321",
    company: "Smoke & Barrel 502",
    title: "Owner",
    city: "Louisville",
    state: "KY",
    country: "US",
    instagram: "smokeandbarrel502",
    relationshipType: "prospect",
    tags: ["restaurant", "louisville", "hot-lead", "bbq"],
    howWeMet: "Marcus Chen introduction at a Louisville food festival",
    introducedBy: "Marcus Chen",
    metDate: "2026-02-01",
    interests: "BBQ competitions, craft beer, muscle cars, KC Chiefs",
    birthday: "1988-06-10",
    relationshipScore: 55,
    importanceScore: 70,
    interactions: [
      { id: "i9", type: "call", date: "2026-03-09", summary: "Demo call — very interested in DerbyFlow ordering system. Hates Toast support.", direction: "outbound", duration: 1800, createdAt: "2026-03-09" },
      { id: "i10", type: "text", date: "2026-03-13", summary: "Texted asking about pricing, sent him the deck", createdAt: "2026-03-13" },
      { id: "i10b", type: "email", date: "2026-03-06", summary: "Initial outreach email — followed up on Marcus's intro", subject: "Marcus Chen said we should connect", createdAt: "2026-03-06" },
      { id: "i10c", type: "social", date: "2026-02-01", summary: "Met at Louisville Food Festival, exchanged cards", createdAt: "2026-02-01" },
    ],
    notes: [
      { id: "n7", content: "Dre is on Toast right now and paying $300/mo. Hates their customer service — called it 'the worst experience of my life.' Hot lead.", pinned: true, category: "business", createdAt: "2026-03-09", updatedAt: "2026-03-09" },
      { id: "n7b", content: "He's won 3 BBQ competitions. Very proud of his brisket. Bring this up in conversation.", category: "personal", createdAt: "2026-03-09", updatedAt: "2026-03-09" },
    ],
    facts: [
      { id: "f10", category: "business", label: "Current provider", value: "Toast ($300/mo)" },
      { id: "f11", category: "business", label: "Monthly revenue", value: "~$80K" },
      { id: "f11b", category: "personal", label: "BBQ competition wins", value: "3" },
      { id: "f11c", category: "business", label: "Seating capacity", value: "85" },
    ],
    opportunities: [
      { id: "o8", title: "DerbyFlow + full digital package", type: "business", status: "in-progress", value: "$500/mo", notes: "Unhappy with Toast, ready to switch. Demo went great.", nextStep: "Send proposal with pricing comparison vs Toast", createdAt: "2026-03-09", updatedAt: "2026-03-13" },
    ],
    aiInsights: [
      { id: "ai6", type: "follow-up-suggested", content: "Dre asked about pricing 2 days ago — send the proposal before he cools off", confidence: 0.94, actionable: true, createdAt: "2026-03-13" },
    ],
    groups: ["Prospects", "Louisville"],
    connections: ["1"],
    lastContactedAt: "2026-03-13",
    nextFollowUp: "2026-03-15",
    source: "Referral",
    aiSummary: "Dre Thompson, owner of Smoke & Barrel 502 and an award-winning pitmaster, is a hot lead for DerbyFlow, highly motivated by his terrible experience with Toast's support. Follow up on the pricing deck, strategically highlighting our superior customer service and connecting personally by mentioning his impressive BBQ competition wins to smoothly close the deal.",
    aiBriefing: "Dre owns Smoke & Barrel 502, a BBQ restaurant doing ~$80K/mo. He's paying Toast $300/mo and hates their customer service. Marcus Chen introduced you at a food festival. The demo call went great and he texted asking about pricing — you need to send the proposal ASAP before he cools off. He's won 3 BBQ competitions and is very proud of his brisket (good conversation topic). He's into muscle cars and the KC Chiefs.",
    createdAt: "2026-02-01",
    updatedAt: "2026-03-13",
    archived: false,
  },
  {
    id: "6",
    firstName: "Hamza",
    lastName: "Ali",
    email: "hamza@derbydigital.us",
    company: "Derby Digital",
    title: "Landing Page Designer",
    city: "Remote",
    relationshipType: "team",
    tags: ["team", "designer"],
    howWeMet: "Hired through Upwork",
    interests: "UI design, gaming, anime",
    relationshipScore: 80,
    interactions: [
      { id: "i11", type: "meeting", date: "2026-03-12", summary: "Weekly sync — working on Bluegrass Garage Door page", recurring: true, createdAt: "2026-03-12" },
      { id: "i11b", type: "text", date: "2026-03-11", summary: "Sent Figma link for the new restaurant landing page template", createdAt: "2026-03-11" },
      { id: "i11c", type: "meeting", date: "2026-03-05", summary: "Weekly sync — reviewed Framer progress", recurring: true, createdAt: "2026-03-05" },
    ],
    notes: [
      { id: "n11", content: "Hamza works best with visual references — send screenshots or Figma links, not just descriptions.", category: "business", createdAt: "2026-02-01", updatedAt: "2026-02-01" },
    ],
    facts: [
      { id: "f12", category: "work", label: "Tools", value: "Framer, WordPress/Elementor, Figma" },
      { id: "f12b", category: "work", label: "Timezone", value: "GMT+5 (Pakistan)" },
      { id: "f12c", category: "work", label: "Availability", value: "Mon-Fri, overlaps EST 8am-12pm" },
    ],
    opportunities: [],
    aiInsights: [],
    groups: ["Team"],
    connections: [],
    lastContactedAt: "2026-03-12",
    source: "Upwork",
    createdAt: "2026-01-15",
    updatedAt: "2026-03-12",
    archived: false,
  },
  {
    id: "7",
    firstName: "Tyler",
    lastName: "Brooks",
    email: "tyler.brooks@gmail.com",
    phone: "+15025558765",
    city: "Louisville",
    state: "KY",
    country: "US",
    instagram: "tylerb_502",
    relationshipType: "friend",
    tags: ["louisville", "school", "close-friend"],
    howWeMet: "UofL freshman year — same dorm floor",
    college: "University of Louisville",
    birthday: "2005-08-30",
    interests: "Basketball, gaming, crypto, sneakers",
    relationshipScore: 90,
    importanceScore: 40,
    interactions: [
      { id: "i12", type: "social", date: "2026-03-13", summary: "Hung out at campus, grabbed lunch at Chick-fil-A", createdAt: "2026-03-13" },
      { id: "i13", type: "text", date: "2026-03-11", summary: "Planning weekend hangout", createdAt: "2026-03-11" },
      { id: "i13b", type: "social", date: "2026-03-07", summary: "Watched the UofL game together", createdAt: "2026-03-07" },
      { id: "i13c", type: "text", date: "2026-03-03", summary: "Sent him a crypto meme", createdAt: "2026-03-03" },
      { id: "i13d", type: "call", date: "2026-02-28", summary: "Late night call about his startup idea", direction: "inbound", duration: 2400, createdAt: "2026-02-28" },
    ],
    notes: [
      { id: "n8", content: "Tyler mentioned his uncle owns 3 restaurants in Bowling Green. Potential intro — ask him about it.", pinned: true, category: "business", createdAt: "2026-03-13", updatedAt: "2026-03-13" },
      { id: "n8b", content: "He's working on a crypto project — wants my advice on marketing. Might be a collab opportunity.", category: "business", createdAt: "2026-02-28", updatedAt: "2026-02-28" },
    ],
    facts: [
      { id: "f13", category: "personal", label: "Favorite game", value: "Valorant" },
      { id: "f13b", category: "personal", label: "Shoe size", value: "11" },
      { id: "f13c", category: "personal", label: "Major", value: "Computer Science" },
    ],
    opportunities: [
      { id: "o9", title: "Uncle's restaurants in Bowling Green", type: "intro", status: "open", notes: "Tyler's uncle owns 3 restaurants — could be 3 new clients", nextStep: "Ask Tyler for intro", createdAt: "2026-03-13", updatedAt: "2026-03-13" },
    ],
    aiInsights: [],
    groups: ["Friends", "School"],
    connections: ["8"],
    lastContactedAt: "2026-03-13",
    source: "School",
    createdAt: "2025-08-20",
    updatedAt: "2026-03-13",
    archived: false,
  },
  {
    id: "8",
    firstName: "Nima",
    lastName: "Asgari",
    email: "nima@asgari.dev",
    phone: "+15025559999",
    company: "Asgari Digital",
    title: "Developer",
    city: "Louisville",
    state: "KY",
    country: "US",
    website: "https://asgari.dev",
    linkedin: "linkedin.com/in/nimaasgari",
    twitter: "nimaasgari",
    relationshipType: "partner",
    tags: ["louisville", "developer", "ai", "potential-partner"],
    howWeMet: "Louisville Tech Meetup — we were both speakers",
    metDate: "2025-10-15",
    interests: "AI, coding, startups, cybersecurity, Persian food",
    college: "Georgia Tech",
    birthday: "1995-04-22",
    relationshipScore: 72,
    importanceScore: 65,
    interactions: [
      { id: "i14", type: "meeting", date: "2026-03-08", summary: "Discussed potential collaboration on AI tools for restaurants", location: "Against the Grain Brewery", duration: 3600, createdAt: "2026-03-08" },
      { id: "i14b", type: "email", date: "2026-02-25", summary: "He shared an AI paper on restaurant demand prediction", subject: "This could be interesting for DerbyFlow", createdAt: "2026-02-25" },
      { id: "i14c", type: "text", date: "2026-03-10", summary: "He texted about a new AI model release — thinks we could use it", createdAt: "2026-03-10" },
    ],
    notes: [
      { id: "n14", content: "Nima has deep AI/ML expertise. Could build the prediction engine for DerbyFlow. Explore partnership vs contractor arrangement.", category: "business", pinned: true, createdAt: "2026-03-08", updatedAt: "2026-03-08" },
    ],
    facts: [
      { id: "f14", category: "business", label: "Speciality", value: "AI/ML, full-stack development" },
      { id: "f14b", category: "business", label: "Hourly rate", value: "$150/hr" },
      { id: "f14c", category: "personal", label: "Heritage", value: "Iranian-American" },
    ],
    opportunities: [
      { id: "o10", title: "DerbyFlow AI partnership", type: "collaboration", status: "open", notes: "Build demand prediction engine for restaurants", nextStep: "Draft partnership proposal", createdAt: "2026-03-08", updatedAt: "2026-03-08" },
    ],
    aiInsights: [],
    groups: ["Partners", "Louisville", "Tech"],
    connections: ["7"],
    lastContactedAt: "2026-03-10",
    source: "Event",
    aiSummary: "Hamza is a productive remote landing page designer on our team, and our collaborative work is progressing well. To continue our strong partnership, always send him visual references like Figma links, and consider connecting over shared interests in UI design or even gaming.",
    aiBriefing: "Nima runs Asgari Digital and specializes in AI/ML and full-stack development ($150/hr). You met at a Louisville Tech Meetup where you were both speakers. He's interested in collaborating on AI features for DerbyFlow, specifically a demand prediction engine for restaurants. He shared a relevant AI paper and is clearly enthusiastic about the space. Georgia Tech grad, Iranian-American, into Persian food and cybersecurity. Consider a partnership proposal vs straight contractor relationship.",
    createdAt: "2025-10-15",
    updatedAt: "2026-03-10",
    archived: false,
  },
  {
    id: "9",
    firstName: "Lisa",
    lastName: "Drayton",
    email: "bbmtryoncatering@gmail.com",
    phone: "+17046540329",
    company: "BBM Tryon Catering",
    title: "Owner",
    city: "Charlotte",
    state: "NC",
    country: "US",
    relationshipType: "prospect",
    tags: ["restaurant", "cold-email", "spothopper", "interested"],
    howWeMet: "Cold email campaign — SpotHopper steal campaign",
    metDate: "2026-03-13",
    relationshipScore: 35,
    importanceScore: 60,
    interactions: [
      { id: "i15", type: "email", date: "2026-03-13", summary: "Replied interested, gave phone number, wants a call", subject: "Re: Better alternative to SpotHopper", sentiment: "positive", createdAt: "2026-03-13" },
      { id: "i15b", type: "email", date: "2026-03-11", summary: "Initial cold email sent", subject: "Better alternative to SpotHopper", createdAt: "2026-03-11" },
    ],
    notes: [
      { id: "n9", content: "Currently on SpotHopper. Interested in conversation and more info. Call her at 704-654-0329. She replied fast — high intent.", pinned: true, category: "business", createdAt: "2026-03-13", updatedAt: "2026-03-13" },
    ],
    facts: [
      { id: "f15", category: "business", label: "Current provider", value: "SpotHopper" },
      { id: "f15b", category: "business", label: "Business type", value: "Catering" },
    ],
    opportunities: [
      { id: "o11", title: "Switch from SpotHopper", type: "business", status: "open", notes: "High intent — gave phone number proactively", nextStep: "Call her ASAP", createdAt: "2026-03-13", updatedAt: "2026-03-13" },
    ],
    aiInsights: [
      { id: "ai7", type: "follow-up-suggested", content: "Lisa gave her phone number proactively — very high intent. Call within 24 hours.", confidence: 0.96, actionable: true, createdAt: "2026-03-13" },
    ],
    groups: ["Prospects"],
    connections: [],
    lastContactedAt: "2026-03-13",
    nextFollowUp: "2026-03-14",
    source: "Cold Email",
    aiSummary: "Tyler is a really engaged, close friend from UofL, sharing his passions for gaming, crypto, and startup ideas, indicating a strong and active relationship. Let's follow up on his crypto project by offering that marketing advice and exploring a collaboration, and remember to ask him more about his uncle's restaurants in Bowling Green.",
    aiBriefing: "Lisa owns BBM Tryon Catering in Charlotte, NC. She replied to your SpotHopper steal campaign within 2 days and proactively gave her phone number — this is very high intent. She's currently on SpotHopper. Call her at 704-654-0329 as soon as possible. This is a catering business, so the pitch should emphasize online ordering, menu management, and event booking features.",
    createdAt: "2026-03-13",
    updatedAt: "2026-03-13",
    archived: false,
  },
  {
    id: "10",
    firstName: "Mom",
    lastName: "",
    phone: "+15025550001",
    city: "Louisville",
    state: "KY",
    country: "US",
    relationshipType: "family",
    tags: ["family"],
    birthday: "1975-09-12",
    interests: "Cooking, gardening, church",
    relationshipScore: 100,
    importanceScore: 100,
    interactions: [
      { id: "i16", type: "call", date: "2026-03-12", summary: "Called to check in — she's proud of the business growth", direction: "outbound", duration: 1200, createdAt: "2026-03-12" },
      { id: "i16b", type: "call", date: "2026-03-08", summary: "She called to remind me about Sunday dinner", direction: "inbound", duration: 300, createdAt: "2026-03-08" },
      { id: "i16c", type: "social", date: "2026-03-10", summary: "Sunday dinner at home", createdAt: "2026-03-10" },
    ],
    notes: [
      { id: "n10", content: "She wants me to come to Sunday dinner more often. Promised to try for every other week.", category: "personal", createdAt: "2026-03-10", updatedAt: "2026-03-10" },
    ],
    facts: [
      { id: "f16", category: "personal", label: "Favorite flowers", value: "Sunflowers" },
      { id: "f16b", category: "personal", label: "Church", value: "Southeast Christian Church" },
    ],
    opportunities: [],
    aiInsights: [],
    groups: ["Family"],
    connections: [],
    stayInTouch: { frequency: "weekly" },
    lastContactedAt: "2026-03-12",
    source: "Family",
    createdAt: "2025-01-01",
    updatedAt: "2026-03-12",
    archived: false,
  },
];
