export type SpotHopperLead = {
  restaurant_name: string;
  website: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  email: string;
  cuisine: string;
  facebook: string;
  instagram: string;
  region: string;
  notes: string;
};

export const SPOTHOPPER_LEADS: SpotHopperLead[] = [
  {
    "restaurant_name": "Barrel House Distilling Co",
    "website": "barrelhousedistillery.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592590159",
    "email": "info@barrelhousedistillery.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/43808893071",
    "instagram": "https://www.instagram.com/barrelhousedistillingco",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sumo Hibachi & Sushi",
    "website": "sumohibachilex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8595546002",
    "email": "linawei4348@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/111999083999305",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Oasis Mediterranean Restaurant",
    "website": "oasisrestaurant.org",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592696440",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101792795938971",
    "instagram": "https://www.instagram.com/oasisrestaurantlex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Coffee, Comics and Games",
    "website": "chaoticgoodlex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593038668",
    "email": "chaoticgoodcg@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/100494109474033",
    "instagram": "https://www.instagram.com/chaoticgoodccg",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Joe Bologna's Restaurant",
    "website": "joebolognas.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592524933",
    "email": "joebolognasrestaurant@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/547172861815539",
    "instagram": "https://www.instagram.com/joebolognasrestaurantllc",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Shake N Crave",
    "website": "shakencrave.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593090029",
    "email": "info@shakencrave.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/61553626200201",
    "instagram": "https://www.instagram.com/shakencrave_lex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Lexington Tea and Brie",
    "website": "lexingtonteaandbrie.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593034337",
    "email": "lexingtonteaandbrie@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/280838345113227",
    "instagram": "https://www.instagram.com/lexingtonteaandbrie",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "West Coast Gourmet Pizza",
    "website": "westcoastgourmetpizza.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593178234",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/372807569424420",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Greenery: Coffee + Social Space",
    "website": "thegreenerylex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "info@thegreenerylex.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/514641731732574",
    "instagram": "https://www.instagram.com/thegreenerylex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Everything Spuds",
    "website": "everythingspuds.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593034881",
    "email": "ericrmstrng1@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/351560604714786",
    "instagram": "https://www.instagram.com/everything_spuds_",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mileta",
    "website": "miletarestaurant.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593038855",
    "email": "mileta@sprouthouseagency.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/61562654531057",
    "instagram": "https://www.instagram.com/miletarestaurant",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Grimes's Fast Food",
    "website": "grimessfastfood.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8595238222",
    "email": "taylor.grimes@live.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/674417755764877",
    "instagram": "https://www.instagram.com/grimessfastfood",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Zundo Izakaya",
    "website": "zundolexington.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593037981",
    "email": "zundolex@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/108126715347078",
    "instagram": "https://www.instagram.com/zundo_izakaya",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Son of a Burger",
    "website": "sonofaburgerllc.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594875479",
    "email": "soblexington@icloud.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/704605869405255",
    "instagram": "https://www.instagram.com/sonofaburger1",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "girlsgirlsgirls Burritos",
    "website": "girlsgirlsgirlsburritos.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592856853",
    "email": "hello@girlsgirlsgirlsburritos.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1829731757057725",
    "instagram": "https://www.instagram.com/girlsgirlsgirlsburritos",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "El Charro Authentic Mexican Cuisine",
    "website": "elcharrolex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592190200",
    "email": "flor.gonzalez@icloud.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/103498863119230",
    "instagram": "https://www.instagram.com/elcharrolex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Stein's by Addie's",
    "website": "steinslex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8599677014",
    "email": "linda@steinslex.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/2201839680081231",
    "instagram": "https://www.instagram.com/steinsbyaddies",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Willow",
    "website": "thewillowlex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594204150",
    "email": "hello@thewillowlex.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/527696940424953",
    "instagram": "https://www.instagram.com/thewillowlex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Ricardo's Grill & Pub",
    "website": "ricardosgrillandpub.com",
    "address": "",
    "city": "Versailles",
    "state": "KY",
    "zip": "",
    "phone": "8598733663",
    "email": "ricardosversailles@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/278100982355958",
    "instagram": "https://www.instagram.com/ricardospub",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Brasa's Restaurant",
    "website": "brasasrestlex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593687080",
    "email": "brasasrestlex@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101747119114260",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Charlie Brown's Restaurant",
    "website": "charliebrownslex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592695701",
    "email": "charliebrownslexington@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/108218972176709",
    "instagram": "https://www.instagram.com/charliebrownslexington",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "AJ's Wings & Things",
    "website": "ajswingsandthings.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592243442",
    "email": "info@ajswingsandthings.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/455729450962999",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "OSAKA",
    "website": "osakalexingtonky.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592962625",
    "email": "mistersunshinekyllc@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/477588532111330",
    "instagram": "https://www.instagram.com/osaka_mastersonstation",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Char",
    "website": "char-on-ashland.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594071100",
    "email": "contact@char-on-ashland.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/364199370107298",
    "instagram": "https://www.instagram.com/char_on_ashland",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Shaking Seafood & Wings",
    "website": "shakingseafoodlexington.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592648888",
    "email": "shakingseafood3110@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/213599649576153",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Elkhorn Tavern",
    "website": "elkhorntavern.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593688122",
    "email": "info@barrelhousedistillery.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/625887224285773",
    "instagram": "https://www.instagram.com/theelkhorntavern",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "World of Gourmet",
    "website": "worldofgourmet.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592869990",
    "email": "",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "NuHealth Kitchen",
    "website": "nuhealthkitchen.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594071565",
    "email": "justin@nuhealthlifestyle.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101898579407018",
    "instagram": "https://www.instagram.com/nuhealthkitchen",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "La Petite Delicat",
    "website": "lapetitedelicat.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592660041",
    "email": "sherrin@lapetitedelicat.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/61556437890907",
    "instagram": "https://www.instagram.com/lapetitedelicat",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Proud Mary BBQ",
    "website": "proudmarybbq.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8599135611",
    "email": "proudmarybbq@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/Proudmarybbq",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Jasmine Rice Thai Restaurant",
    "website": "jasminericethailex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593034986",
    "email": "jasminerice8@hotmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/117594278310717",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Old North Bar",
    "website": "oldnorthbar.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8596198387",
    "email": "oldnorthbar@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/104135498578980",
    "instagram": "https://www.instagram.com/oldnorthbar",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mami Monchitas",
    "website": "mamimonchitas.com",
    "address": "",
    "city": "Frankfort",
    "state": "KY",
    "zip": "",
    "phone": "5026992380",
    "email": "mamimonchitas@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1880501405600270",
    "instagram": "https://www.instagram.com/mami_monchitas_restaurant_",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Paisano's Italian Restaurant & Lounge",
    "website": "paisanoslex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592775321",
    "email": "markkakar@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/211562490690",
    "instagram": "https://www.instagram.com/paisanositalianristorante",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Toku Revolving Sushi",
    "website": "tokusushibar.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593689992",
    "email": "zundolex@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/368134523052310",
    "instagram": "https://www.instagram.com/tokurevolving",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Rolling Oven Taproom",
    "website": "rollingoven.com",
    "address": "",
    "city": "Versailles",
    "state": "KY",
    "zip": "",
    "phone": "8592560007",
    "email": "rollingovenstore@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/539115806539095",
    "instagram": "https://www.instagram.com/rollingoventaproom",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Ghost Fox Winery",
    "website": "ghostfoxwinery.com",
    "address": "",
    "city": "Nicholasville",
    "state": "KY",
    "zip": "",
    "phone": "5025538378",
    "email": "hello@ghostfoxwinery.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/102450516062911",
    "instagram": "https://www.instagram.com/ghostfoxwinery",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Asuka Japanese Steak House & Sushi",
    "website": "asukagrill.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592720020",
    "email": "asukagrill@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/111062985577588",
    "instagram": "https://www.instagram.com/asukagrill",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Jump Start Smoothies",
    "website": "jumpstartsmoothies.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593093442",
    "email": "john@jumpstartsmoothies.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/106922060946178",
    "instagram": "https://www.instagram.com/jumpstartsmoothies",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Beau's Cafe",
    "website": "beauscafe.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593034167",
    "email": "beauscafelex@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/163405186851589",
    "instagram": "https://www.instagram.com/beauscafelex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Burger Joint",
    "website": "theburgerjointky.com",
    "address": "",
    "city": "Georgetown",
    "state": "KY",
    "zip": "",
    "phone": "5023198174",
    "email": "Burgerjointky@outlook.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/821728274352145",
    "instagram": "https://www.instagram.com/burgerjoint2025",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Chinkapin Brewing",
    "website": "chinkapinbrewing.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593098476",
    "email": "chinkapinbrewing@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/116940801394758",
    "instagram": "https://www.instagram.com/chinkapinbrewing",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Rodney's on Broadway",
    "website": "rodneysonbroadway.com",
    "address": "",
    "city": "Georgetown",
    "state": "KY",
    "zip": "",
    "phone": "5028687637",
    "email": "erica@rodneysonbroadway.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/190891744270931",
    "instagram": "https://www.instagram.com/rodsonbroadway",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Dave's Blazin BBQ",
    "website": "davesblazinbbqky.com",
    "address": "",
    "city": "Georgetown",
    "state": "KY",
    "zip": "",
    "phone": "5023198325",
    "email": "davesblazinbbq@yahoo.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/davesblazinbbq",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Irie Flavors",
    "website": "irieflavors.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594605925",
    "email": "irieflavaz@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/irieflavorsrestaurant/",
    "instagram": "https://www.instagram.com/irie_flavorsky",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Prodigy Vineyards & Winery",
    "website": "prodigyvineyards.com",
    "address": "",
    "city": "Frankfort",
    "state": "KY",
    "zip": "",
    "phone": "5023529400",
    "email": "prodigywines@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/208782028995630",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Waterfront Grill and Gathering",
    "website": "kentuckywaterfrontgrill.com",
    "address": "",
    "city": "Boonesboro",
    "state": "KY",
    "zip": "",
    "phone": "8595956003",
    "email": "waterfrontadvertising@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/fosterrestaurantsea",
    "instagram": "https://www.instagram.com/fosterrestaurant",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Joe Brett's Ice Cream",
    "website": "jbicusa.com",
    "address": "",
    "city": "Winchester",
    "state": "KY",
    "zip": "",
    "phone": "8596445060",
    "email": "infojoebretts@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/361361861357091",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Hall's on the River",
    "website": "hallsontheriver.com",
    "address": "",
    "city": "Winchester",
    "state": "KY",
    "zip": "",
    "phone": "8595276620",
    "email": "contact@hallsontheriver.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/218927328127697",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Blessed Bro's Bar & Grill",
    "website": "lexingtonchickenwingsrestaurant.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593034020",
    "email": "brothersbarandgrilllexington@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/102947166109970",
    "instagram": "https://www.instagram.com/blessedbrosbarandgrill",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "El Charro",
    "website": "myelcharrotexano.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8595757113",
    "email": "elcharrotexano@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/100129631945519",
    "instagram": "https://www.instagram.com/el_charro_texano",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Arcadium",
    "website": "arcadiumbar.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593179712",
    "email": "info@arcadiumbar.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/409735345740675",
    "instagram": "https://www.instagram.com/arcadiumlex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Gillum's Sports Lounge",
    "website": "island.gillumssportslounge.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593535450",
    "email": "playersclubky@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/100092517034735",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Bespoke Bakery",
    "website": "bespokebakerycafe.com",
    "address": "",
    "city": "Richmond",
    "state": "KY",
    "zip": "",
    "phone": "8593535048",
    "email": "bespokebakerycafe@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/bespokebakerycafe",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Bert's SpeakCheezy",
    "website": "bertsspeakcheezy.com",
    "address": "",
    "city": "Berea",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "Bertsspeakcheezy@hotmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/bertsspeakcheezy",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Bumble Bites",
    "website": "bumblebitestea.com",
    "address": "",
    "city": "Richmond",
    "state": "KY",
    "zip": "",
    "phone": "8593538043",
    "email": "bumblebites@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/103862028628868",
    "instagram": "https://www.instagram.com/bumblebites",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mr Brews Taphouse",
    "website": "lexington.mrbrewstaphouse.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592191931",
    "email": "ncanavera@mrbrewstaphouse.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1988885491322879",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Wing KYng",
    "website": "wingkyng.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8597851661",
    "email": "wingkyng859@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1337167369766049",
    "instagram": "https://www.instagram.com/wingkyng859",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Ume Craft Ramen",
    "website": "umeramen.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594699800",
    "email": "umecraftramen@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/105813775709718",
    "instagram": "https://www.instagram.com/umecraftramen",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Serafini",
    "website": "serafinifrankfort.com",
    "address": "",
    "city": "Frankfort",
    "state": "KY",
    "zip": "",
    "phone": "5028755599",
    "email": "taylor@serafinikentucky.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/148791965144965",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Perico's Mexican Restaurant",
    "website": "pericosparisky.com",
    "address": "",
    "city": "Paris",
    "state": "KY",
    "zip": "",
    "phone": "8599885421",
    "email": "pericosmexicanrestaurant@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/376405413187073",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Cafe",
    "website": "thecafetogo.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5025899191",
    "email": "info@thecafetogo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/210748222328758",
    "instagram": "https://www.instagram.com/thecafelville",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Wick + Mortar Studio",
    "website": "wickandmortarstudio.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8597402325",
    "email": "wickandmortarstudio@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/100083412345432",
    "instagram": "https://www.instagram.com/wickandmortarstudio",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Papi's at Palomar",
    "website": "palomar.papislex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8595232806",
    "email": "megganhuynh372@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/391028394709310",
    "instagram": "https://www.instagram.com/papislex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Southern Cookhouse & Bar",
    "website": "southerncookhousebar.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8597852194",
    "email": "bryan@southerncookhousebar.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mexico mi amor",
    "website": "mexicomiamorky.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8593036102",
    "email": "roxanaher17@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/110504972017085",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "El Mariachi-Hamburg",
    "website": "elmariachilexington.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8595549718",
    "email": "elmariachilex@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/106958011093710",
    "instagram": "https://www.instagram.com/elmariachi_lex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Black Type Brewing",
    "website": "blk-type.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594566274",
    "email": "Alberta@blk-type.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/641914185666241",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Papi's Citation",
    "website": "citation.papislex.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8592869747",
    "email": "megganhuynh372@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/391028394709310",
    "instagram": "https://www.instagram.com/papislex",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Moody Mike's",
    "website": "moodymikes.org",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "8594337633",
    "email": "moodymikes18@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1246282825526753",
    "instagram": "https://www.instagram.com/moody_mikes",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Shades Caf\u00e9 & Steakhouse",
    "website": "shadessteakhouse.com",
    "address": "",
    "city": "Middlesboro",
    "state": "KY",
    "zip": "",
    "phone": "6062484315",
    "email": "shadessteakhouse@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Taco Choza",
    "website": "tacochoza.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5024095080",
    "email": "tacochozaky1@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/2213172858925225",
    "instagram": "",
    "region": "Lexington",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Fish House",
    "website": "fishhouselouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5025682993",
    "email": "Thefishhouseandcafebeignet@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/102794338029140",
    "instagram": "https://www.instagram.com/thefishhouseandcafebeignet",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Check's Cafe",
    "website": "checkscafe.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026379515",
    "email": "checkscafe@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sidebar at Whiskey Row",
    "website": "sidebaratwhiskey.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026302012",
    "email": "",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/sidebarwhiskeyrow",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Yummy Pollo",
    "website": "yummypollo.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026181400",
    "email": "myyummypollo@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/people/Yummy-Pollo/100064119333703/",
    "instagram": "https://www.instagram.com/yummypolloky",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Hereafter",
    "website": "hereafterlou.com",
    "address": "",
    "city": "Lexington",
    "state": "KY",
    "zip": "",
    "phone": "5023847820",
    "email": "meetme@hereafterlou.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/227862830399667",
    "instagram": "https://www.instagram.com/meetmehereafter",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Decade",
    "website": "decaderestaurant.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5027490110",
    "email": "andy@decaderestaurant.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/decaderestaurant",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sol Aztecas Mexican Restaurant",
    "website": "solaztecasrestaurant.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5024597776",
    "email": "solaztecas2427@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/109618357218472",
    "instagram": "https://www.instagram.com/solaztecasrestaurant",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sakura Blue",
    "website": "sakurabluelouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5028973600",
    "email": "sakurabluelouisville@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Holy Smokes BBQ & Catering",
    "website": "holysmokesbbq.store",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5029685657",
    "email": "terry@holysmokesbbq.store",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Palm Room",
    "website": "thepalmroom502.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5029996800",
    "email": "thepalmroom2@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/102695568968205",
    "instagram": "https://www.instagram.com/Palmroom502",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Hiko a Mon",
    "website": "hikoamon-louisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023651651",
    "email": "hikoamon@twc.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/369651961264",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Dasha Barbours",
    "website": "dbsbistro.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5028822081",
    "email": "dashabarbour@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/723880340969000",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Martini Italian Bistro",
    "website": "martinilouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023949797",
    "email": "martini@martinilouisville.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/227883325474",
    "instagram": "https://www.instagram.com/martiniitalianbistro",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Granville Pub",
    "website": "thegranvillepub.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026362748",
    "email": "thegranvillepub@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/107901231969437",
    "instagram": "https://www.instagram.com/thegranvillepub",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Cheddar Box Too",
    "website": "cheddarboxtoo.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5028961133",
    "email": "info@cheddarboxtoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/515386141840089",
    "instagram": "https://www.instagram.com/cheddarboxtoolouisville",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sapporo Japanese Grill and Sushi",
    "website": "sapporolouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5024795550",
    "email": "mikimsapporo@yahoo.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Juno",
    "website": "junorestaurants.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026322777",
    "email": "junorestaurants@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Blind Squirrel LOUISVILLE",
    "website": "blindsquirrellouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023846761",
    "email": "info@blindsquirrelrestaurant.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/120924418446833",
    "instagram": "https://www.instagram.com/blindsquirrelrestaurant",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "District 6",
    "website": "district6gastropub.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5028735561",
    "email": "EatDistrict6@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101074901292913",
    "instagram": "https://www.instagram.com/district_6_gastropub",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Misawa Hibachi & Sushi Bar",
    "website": "misawalouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5022901780",
    "email": "misawalouisville@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1926285847492868",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The GRUV Sports Bar & Lounge",
    "website": "thegruvlou.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5029635448",
    "email": "thegruvlou@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/115083804420338",
    "instagram": "https://www.instagram.com/thegruvlou",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Garage Bar",
    "website": "garageonmarket.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5025417124",
    "email": "30dollarbill@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/154439154621562",
    "instagram": "https://www.instagram.com/garageonmarket",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "El Mundo",
    "website": "502elmundo.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023845633",
    "email": "hola@502elmundo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/tr",
    "instagram": "https://www.instagram.com/502elmundo",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "La Suerte",
    "website": "lasuerteky.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/398503740972109",
    "instagram": "https://www.instagram.com/lasuertelouisville",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Abyssinia",
    "website": "abyssinialouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023848347",
    "email": "arefianereda@yahoo.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Gracious Plenty",
    "website": "graciousplentycatering.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026184755",
    "email": "info@graciousplentycatering.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/939134606145141",
    "instagram": "https://www.instagram.com/gracious_plenty",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "3rd Turn Brewing",
    "website": "jeffersontown.3rdturnbrewing.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5024823373",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1103917686301144",
    "instagram": "https://www.instagram.com/3rdturnbrewing",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "3rd Turn Oldham Gardens",
    "website": "oldhamgardens.3rdturnbrewing.com",
    "address": "",
    "city": "Crestwood",
    "state": "KY",
    "zip": "",
    "phone": "5022337591",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/135607537070770",
    "instagram": "https://www.instagram.com/3rdturnoldhamgardens",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Dairy Kastle",
    "website": "dairykastle.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026348990",
    "email": "dairykastle1976@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/302031192983604",
    "instagram": "https://www.instagram.com/dairykastle",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Highland Morning",
    "website": "highlandmorningky.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023653900",
    "email": "highlandmorning@yahoo.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Las Margaritas Mexican Cuisine",
    "website": "lasmargaritasresturant.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026908071",
    "email": "lasmargaritasky2@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/margaritas307",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Old School NY Pizza",
    "website": "prospect.oldschoolnypizza.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5028823000",
    "email": "info@oldschoolnypizza.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Los Aztecas Mexican Restaurant",
    "website": "losaztecasnulu.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5025618535",
    "email": "contact@losaztecasnulu.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1449427525273322",
    "instagram": "https://www.instagram.com/losaztecasnulu",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Jojo's Cajun Cuisine",
    "website": "jojosnewalbany.com",
    "address": "",
    "city": "New Albany",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "jojosnewalbany@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/760038020521214",
    "instagram": "https://www.instagram.com/jojosnewalbany",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Palermo's Italian Restaurant",
    "website": "palermositalianrestaurant.com",
    "address": "",
    "city": "La Grange",
    "state": "KY",
    "zip": "",
    "phone": "5022650039",
    "email": "palermositalianrestaurant24@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/511691322036481",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Shack in The Back BBQ",
    "website": "shackinthebackbbq.com",
    "address": "",
    "city": "Fairdale",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "info@shackinthebackbbq.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/shackinthebackbbq",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Chocolate Lab",
    "website": "chocolatelabdesserts.com",
    "address": "",
    "city": "Radcliff",
    "state": "KY",
    "zip": "",
    "phone": "2703600079",
    "email": "chocolate.lab.radcliff@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/457752900765364",
    "instagram": "https://www.instagram.com/chocolate_lab_and_desserts",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Flanagan's Ale House",
    "website": "flanagansalehouse.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5025853700",
    "email": "drewpb42189@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/flanagans_ale_house",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "El Catrin Mexican Grill",
    "website": "elcatrin-mexicangrill.com",
    "address": "",
    "city": "Mount Washington",
    "state": "KY",
    "zip": "",
    "phone": "5022515011",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/477346238784973",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Los Tres Amigos",
    "website": "joseylostresamigos.com",
    "address": "",
    "city": "Bardstown",
    "state": "KY",
    "zip": "",
    "phone": "5025077988",
    "email": "Juanairis0322@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/102531555643665",
    "instagram": "https://www.instagram.com/juanairis22",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Umami Sushi",
    "website": "umamisushi.net",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023310179",
    "email": "unclkm@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/472354752966633",
    "instagram": "https://www.instagram.com/umamibardstown",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "PG&J's Dog Bar",
    "website": "pgjdogbar.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026306350",
    "email": "info.louisville@pgjdogbar.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/431706764069882",
    "instagram": "https://www.instagram.com/pgjdogbar",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "GOGi 1055 Korean BBQ",
    "website": "gogi1055.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5027490049",
    "email": "mikimsapporo@yahoo.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/gogi.1055.kbbq",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Cedarwood Restaurant",
    "website": "cedarwoodrestaurant.com",
    "address": "",
    "city": "Lebanon",
    "state": "KY",
    "zip": "",
    "phone": "2706924474",
    "email": "cedarwoodrest@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/200687999972560",
    "instagram": "https://www.instagram.com/cedarwoodrestaurant",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Yi Sushi Omakase",
    "website": "yisushiomakase.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023840353",
    "email": "yiomakaseky@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/555203831019161",
    "instagram": "https://www.instagram.com/yisushiomakase",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mi Casita",
    "website": "micasita-shelbyville.com",
    "address": "",
    "city": "Shelbyville",
    "state": "KY",
    "zip": "",
    "phone": "5024372113",
    "email": "alejandro6738@hotmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "El Comal",
    "website": "elcomalky.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026322053",
    "email": "elcomaldixie@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/103905551153132",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "La Cabanita Mexican Grill",
    "website": "lacabanita-mex.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026145075",
    "email": "lacabanitaky@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/105974025509497",
    "instagram": "https://www.instagram.com/lacabanitamexicangrill",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Falls City Beer",
    "website": "fallscitybeer.com",
    "address": "",
    "city": "NuLu",
    "state": "KY",
    "zip": "",
    "phone": "5022577147",
    "email": "Info@fallscitybeer.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/219346130375",
    "instagram": "https://www.instagram.com/fallscitybeer",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Home Plate Family Restaurant",
    "website": "homeplatefamilyrestaurant.com",
    "address": "",
    "city": "Brandenburg",
    "state": "KY",
    "zip": "",
    "phone": "2704221759",
    "email": "italianfarmhouse2019@outlook.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Jump Start Smoothies- NULU",
    "website": "nulu.jumpstartsmoothies.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5023652498",
    "email": "john@jumpstartsmoothies.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/106922060946178",
    "instagram": "https://www.instagram.com/jumpstartsmoothies",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Shopey's Pizza",
    "website": "shopeyslouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "jaynelson13027@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/2011460905844852",
    "instagram": "https://www.instagram.com/shopeyspizzalouisville",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mile Wide Beer Co.",
    "website": "milewidebeer.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5024098139",
    "email": "aaron@milewidebeer.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1003299893100236",
    "instagram": "https://www.instagram.com/milewidebeer",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Dairy Del",
    "website": "dairydel.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5027094660",
    "email": "dairydelgermantown@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "https://www.instagram.com/dairy.del",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Mag Bar",
    "website": "magbarlouisville.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5026379052",
    "email": "booking@magbarlouisville.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/129740297064154",
    "instagram": "https://www.instagram.com/magbarlouisville",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Pizzaville Sports Bar",
    "website": "pizzavillepizza.com",
    "address": "",
    "city": "Louisville",
    "state": "KY",
    "zip": "",
    "phone": "5027543001",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/104332654904545",
    "instagram": "https://www.instagram.com/pizzavillepizza",
    "region": "Louisville",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Overtime Sports Bar & Grill",
    "website": "overtimebg.com",
    "address": "",
    "city": "Bowling Green",
    "state": "KY",
    "zip": "",
    "phone": "2709044430",
    "email": "overtimebg@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/tr",
    "instagram": "https://www.instagram.com/overtimesbg",
    "region": "Bowling Green",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Finish Line Bar & Grill",
    "website": "finishlinebargrillbg.com",
    "address": "",
    "city": "Bowling Green",
    "state": "KY",
    "zip": "",
    "phone": "2707459191",
    "email": "info@finishlinesportsbargrill.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Bowling Green",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Jalisco",
    "website": "jalisco-cantina.com",
    "address": "",
    "city": "Bowling Green",
    "state": "KY",
    "zip": "",
    "phone": "2705990438",
    "email": "jaliscomexicangrillcantina@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/182887391565138",
    "instagram": "https://www.instagram.com/jaliscomexcanbg",
    "region": "Bowling Green",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Brickyard Cafe",
    "website": "brickyardcafefranklin.com",
    "address": "",
    "city": "Franklin",
    "state": "KY",
    "zip": "",
    "phone": "2705869080",
    "email": "brickyardfranklin@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/203969363068468",
    "instagram": "https://www.instagram.com/brickyardcafefranklinky",
    "region": "Bowling Green",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Burger & Bowl",
    "website": "burgerbowl.co",
    "address": "",
    "city": "Bowling Green",
    "state": "KY",
    "zip": "",
    "phone": "2702827732",
    "email": "burgerbowl@outlook.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/374195286503624",
    "instagram": "https://www.instagram.com/burger_bowl",
    "region": "Bowling Green",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Rylan's",
    "website": "rylansrestaurantky.com",
    "address": "",
    "city": "Bowling Green",
    "state": "KY",
    "zip": "",
    "phone": "2702533198",
    "email": "rylansrestaurant@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/100651436764365",
    "instagram": "",
    "region": "Bowling Green",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Works Pizza Co.",
    "website": "theworkspizzacovington.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "8592610414",
    "email": "info@theworkspizzaco.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/319266914606581",
    "instagram": "",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Wabi Sabi",
    "website": "wabisabiky.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "8593996503",
    "email": "jasoncincy@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Zola Pub and Grill",
    "website": "zolapubandgrill.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "8592617510",
    "email": "zolapubandgrill@zoomtown.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/176655040011",
    "instagram": "https://www.instagram.com/zola_pub_and_grill",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Coba Bar and Grill",
    "website": "cobabargrill.com",
    "address": "",
    "city": "Taylor Mill",
    "state": "KY",
    "zip": "",
    "phone": "8594150030",
    "email": "coba.taylormill@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101470139431661",
    "instagram": "https://www.instagram.com/coba.taylormill",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Zapata Cantina",
    "website": "zapata-cantina.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "8598148020",
    "email": "zapata.cov@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/106714204470621",
    "instagram": "https://www.instagram.com/zapata.cov",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sis's on Monmouth",
    "website": "eatatsiss.com",
    "address": "",
    "city": "Newport",
    "state": "KY",
    "zip": "",
    "phone": "8594313157",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/217997692921013",
    "instagram": "https://www.instagram.com/sissonmonmouth",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Pee Wee's Place",
    "website": "peeweesplace.net",
    "address": "",
    "city": "Crescent Springs",
    "state": "KY",
    "zip": "",
    "phone": "8593414977",
    "email": "peeweesplaceky@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/135664802386",
    "instagram": "https://www.instagram.com/peewees.place",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Pensive Distilling Co.",
    "website": "pensivedistilling.com",
    "address": "",
    "city": "Newport",
    "state": "KY",
    "zip": "",
    "phone": "8593605579",
    "email": "Pensivedistilling@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1587024661615163",
    "instagram": "https://www.instagram.com/pensivedistillingco",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Torres",
    "website": "florence.torresmexicansteakhouse.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "8598694090",
    "email": "torres.mexicansteakhouse@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/100049790809848",
    "instagram": "",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Blind Squirrel FLORENCE",
    "website": "blindsquirrelflorence.com",
    "address": "",
    "city": "Florence",
    "state": "KY",
    "zip": "",
    "phone": "8598699886",
    "email": "info@blindsquirrelrestaurant.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/230937658873758",
    "instagram": "https://www.instagram.com/blindsquirrelrestaurant",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Susy's Cakes",
    "website": "susys-cakes.com",
    "address": "",
    "city": "Florence",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "torres.bakery.ky@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/297216260150604",
    "instagram": "https://www.instagram.com/susy.s_cakes",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Matsuya Japanese Restaurant",
    "website": "matsuyajapaneserestaurant.com",
    "address": "",
    "city": "Florence",
    "state": "KY",
    "zip": "",
    "phone": "8597461199",
    "email": "matsuyajapaneserestaurantky@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/567775946429385",
    "instagram": "https://www.instagram.com/matsuya_japanese_restaurant_",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "La Torta Loca",
    "website": "latortalocaky.com",
    "address": "",
    "city": "Crescent Springs",
    "state": "KY",
    "zip": "",
    "phone": "8593602423",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/2133426616875128",
    "instagram": "https://www.instagram.com/latortalocaky",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Agaves",
    "website": "hebronagaves.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "8596895489",
    "email": "diana_toyo@hotmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1747683045477923",
    "instagram": "https://www.instagram.com/agaves_mexican_restaurante_",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Buffalo Bobs Family Restaurant",
    "website": "eatatbobs.com",
    "address": "",
    "city": "Florence",
    "state": "KY",
    "zip": "",
    "phone": "8593715244",
    "email": "Bob@eatatbobs.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Bristol's",
    "website": "liberty-collective.com",
    "address": "",
    "city": "Covington",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "info@liberty-collective.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/profile.php",
    "instagram": "https://www.instagram.com/libertycollectiveoh/",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Greek To Me",
    "website": "greektome.net",
    "address": "",
    "city": "Erlanger",
    "state": "KY",
    "zip": "",
    "phone": "8597273000",
    "email": "georgebetas@greektome.net",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1575222866030006",
    "instagram": "https://www.instagram.com/grk2me",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Noce's Pizzeria",
    "website": "nocespizza.com",
    "address": "",
    "city": "Edgewood",
    "state": "KY",
    "zip": "",
    "phone": "8593316623",
    "email": "nocespizzaedgewood@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/233362322949",
    "instagram": "https://www.instagram.com/nocejay",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Old Millers Tavern",
    "website": "oldmillerstavern.com",
    "address": "",
    "city": "Alexandria ky.",
    "state": "KY",
    "zip": "",
    "phone": "8596356000",
    "email": "oldmillerstavern@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/208432159712802",
    "instagram": "https://www.instagram.com/oldmillerstavern_",
    "region": "Covington-NKY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sig Luscher Brewery",
    "website": "sigluscherbrewery.com",
    "address": "",
    "city": "Frankfort",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "info@sigluscherbrewery.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/197279050889199",
    "instagram": "https://www.instagram.com/sigluscherbrewery",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Linney's Pizza",
    "website": "linneyspizza.com",
    "address": "",
    "city": "Frankfort",
    "state": "KY",
    "zip": "",
    "phone": "5028754685",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/102111112141776",
    "instagram": "https://www.instagram.com/linneyspizza",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Las Margaritas",
    "website": "lasmargaritaslawrenceburg.com",
    "address": "",
    "city": "Lawrenceburg",
    "state": "KY",
    "zip": "",
    "phone": "5023534033",
    "email": "melissahuertagamez@yahoo.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Licho's Mexican Kitchen",
    "website": "lichosmexicankitchen.com",
    "address": "",
    "city": "Lawrenceburg",
    "state": "KY",
    "zip": "",
    "phone": "5023534177",
    "email": "lichosmexicankitchen@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Bricks and Brews",
    "website": "bricksandbrewsdanville.com",
    "address": "",
    "city": "Danville",
    "state": "KY",
    "zip": "",
    "phone": "8592092511",
    "email": "bricksandbrewsdanville@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/103026425666374",
    "instagram": "https://www.instagram.com/bricks_and_brews_of_danville",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Daniels Poke and Ramen",
    "website": "danielspokeramen.com",
    "address": "",
    "city": "Danville",
    "state": "KY",
    "zip": "",
    "phone": "8592094626",
    "email": "danielspokenramen@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101775692888612",
    "instagram": "https://www.instagram.com/danielspokeramen",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "The Nook",
    "website": "thenookdanville.com",
    "address": "",
    "city": "Danville",
    "state": "KY",
    "zip": "",
    "phone": "8594146774",
    "email": "thenookvenue@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/112703740180923",
    "instagram": "https://www.instagram.com/the_nook_music_venue",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Las Margaritas",
    "website": "lasmargaritasofdanville.com",
    "address": "",
    "city": "Frankfort",
    "state": "KY",
    "zip": "",
    "phone": "8592012235",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/106083355745703",
    "instagram": "",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Morley's Backyard",
    "website": "morleysky.com",
    "address": "",
    "city": "Danville",
    "state": "KY",
    "zip": "",
    "phone": "8592092229",
    "email": "events@Morleysky.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/101999702648053",
    "instagram": "https://www.instagram.com/morleysbackyard",
    "region": "Frankfort",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Sobe Eats Culinary Concepts",
    "website": "sobe-eats.com",
    "address": "",
    "city": "Murray",
    "state": "KY",
    "zip": "",
    "phone": "",
    "email": "sobe.eats@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/114093797052011",
    "instagram": "https://www.instagram.com/sobeeatsut",
    "region": "Paducah",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "M & J Rolling Cafe",
    "website": "mjrollingcafe.com",
    "address": "",
    "city": "Ashland",
    "state": "KY",
    "zip": "",
    "phone": "6063270001",
    "email": "jennymarco@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/110709931342564",
    "instagram": "https://www.instagram.com/mandj_andfoodtruck",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Made to Crave",
    "website": "madetocraverestaurant.com",
    "address": "",
    "city": "Eastern KY",
    "state": "KY",
    "zip": "",
    "phone": "6065065038",
    "email": "madetocrave1@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1016707368518343",
    "instagram": "https://www.instagram.com/made.2crave",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Lizzie B's Bakery Cafe",
    "website": "lizziebs.com",
    "address": "",
    "city": "Prestonsburg",
    "state": "KY",
    "zip": "",
    "phone": "6068862844",
    "email": "lbcafe369@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/254890174558957",
    "instagram": "https://www.instagram.com/lizziebscafe",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Santa Fe Mexican Restaurant",
    "website": "santafemexicanky.com",
    "address": "",
    "city": "Corbin",
    "state": "KY",
    "zip": "",
    "phone": "6067220176",
    "email": "aled1885@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Old Town Grill",
    "website": "corbin.oldtowngrillinc.com",
    "address": "",
    "city": "Corbin",
    "state": "KY",
    "zip": "",
    "phone": "6065235515",
    "email": "otgcorbin@yahoo.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1465904313709858",
    "instagram": "",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Torres Mexican Steakhouse",
    "website": "williamsburg.torresmexicansteakhouse.com",
    "address": "",
    "city": "Williamsburg",
    "state": "KY",
    "zip": "",
    "phone": "6065156132",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/846590998804313",
    "instagram": "",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Shiloh Steakhouse",
    "website": "shilohsteakhouse.com",
    "address": "",
    "city": "London",
    "state": "KY",
    "zip": "",
    "phone": "6068779363",
    "email": "apowell@shilohexpress.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/499825270134091",
    "instagram": "https://www.instagram.com/shilohsteakhouse",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Los Rodeos",
    "website": "losrodeos-ky.com",
    "address": "",
    "city": "Eastern KY",
    "state": "KY",
    "zip": "",
    "phone": "8594972988",
    "email": "losrodeosinc@gmail.com",
    "cuisine": "",
    "facebook": "",
    "instagram": "",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Tomatoes & Flames",
    "website": "tandfpizza.com",
    "address": "",
    "city": "Mount Sterling",
    "state": "KY",
    "zip": "",
    "phone": "8595203723",
    "email": "tomatoesandflames@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/228548770829701",
    "instagram": "https://www.instagram.com/tomatoesandflames",
    "region": "Eastern KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Woo Hoo",
    "website": "woohooetown.com",
    "address": "",
    "city": "Central KY",
    "state": "KY",
    "zip": "",
    "phone": "2709000214",
    "email": "woohooetown@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/1004081502979135",
    "instagram": "https://www.instagram.com/woohooetown",
    "region": "Central KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Deez Butts BBQ",
    "website": "deezbuttsbbqky.com",
    "address": "",
    "city": "Elizabethtown",
    "state": "KY",
    "zip": "",
    "phone": "2707356935",
    "email": "",
    "cuisine": "",
    "facebook": "https://www.facebook.com/893263687416485",
    "instagram": "",
    "region": "Central KY",
    "notes": "Verified SpotHopper"
  },
  {
    "restaurant_name": "Wings Pizza N Things",
    "website": "wpntcampbellsville.com",
    "address": "",
    "city": "Campbellsville",
    "state": "KY",
    "zip": "",
    "phone": "2702834923",
    "email": "whitney.wpntky@gmail.com",
    "cuisine": "",
    "facebook": "https://www.facebook.com/434791699726865",
    "instagram": "https://www.instagram.com/wingspizzanthings.ky",
    "region": "Central KY",
    "notes": "Verified SpotHopper"
  }
];
